
//START NAVIGATION SECTION
	// JUMP LINK SCROLL
	// https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_eff_animate_smoothscroll
	// WHEN USER SELECTS NAVIGATION OPTION
	// PAGE WILL SMOOTH SCROLL TO DESIRED SECTION WITH #SECTION-NAME
//END NAVIGATION SECTION





//START SECTION 1: MUSIC ALBUM HIGHLIGHT
	// NO INTERACTIONS FOR THIS SECTION
//END SECTION 1: MUSIC ALBUM HIGHLIGHT





//START SECTION 2: TOUR DATES
	// MODAL WINDOW - POP-UP "SOLD OUT"
	// https://www.w3schools.com/bootstrap/bootstrap_modal.asp
	// WHEN USER SELECTS "BUY NOW" BUTTON OPTION
		// MODAL WINDOW POP-UP SLIDES ACROSS SCREEN TO CENTER-ALIGN
		// COPY DISPLAYS "SOLD OUT - PLEASE SEE OTHER TOUR DATES FOR PURCHASE"
	// WHEN USER CLOSES WINDOW, MODAL WINDOW FADES OUT SMOOTHLY
//END SECTION 2: TOUR DATES





//START SECTION 3: LIVE PERFORMANCES
	// CAROUSEL SCRIPT
	// https://www.w3schools.com/bootstrap/bootstrap_carousel.asp
	// USER HAS THE OPTION TO VIEW 3 VIDEOS IN THE CAROUSEL 
		// THERE IS A NEXT, PREVIOUS, AND nth INDICATION OF WHICH VIDEO YOU ARE VIEWING 
		// IN RELATION TO THE OTHER VIDEOS
//END SECTION 3: LIVE PERFORMANCE





//START SECTION 4: ABOUT
	// FLEXBOX
//END SECTION SECTION 4: ABOUT







